### ISSUE TITLE
[Client Update] Feedback on Initial Scrape GMA

### ISSUE THREAD

**Issue by stefsy** [SiliconValleyInsight/in-the-news#1]
Grab raw data for all of 2014 

Filter out
* articles from Reuters (all international, not relevant)

**Comment by antoniocarlosortiz** [comment]
Oh ok. So should we remove this from the output of the scraper or do we do this manually ourselves after the csv has been created?

**Comment by stefsy** [comment]
get raw data (article list, urls, and titles) for all articles in 2014. could be interesting data for future analysis!

**Comment by antoniocarlosortiz** [comment]
This has already been done. May I ask if i can already close the issue?
