### ISSUE TITLE
User can filter articles according to whether or not the survey has been completed.

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#10]
User can filter the articles according to whether or not the survey has been completed. Clicking on "Yes" filters out articles that have not been surveyed, clicking on "No" filters out articles that have been surveyed. This way, the user knows which articles remain left to be surveyed, and which are done. Active filter is displayed in bold.

![screen shot 2015-04-29 at 5 23 31 pm](https://cloud.githubusercontent.com/assets/1260018/7388128/681e7206-ee95-11e4-9d80-cb33356d73f4.png)

**Comment by antoniocarlosortiz** [comment]
On track to finish by EOD

**Comment by antoniocarlosortiz** [comment]
@piafaustino for your review.

**Comment by piafaustino** [comment]
Yes this works. However, I recommend an enhancement all all filter functionalities by enabling multiple simultaneous filters. Made a new issue for it: #24. Will close this one now.
