### ISSUE TITLE
For any "tick all that apply" question, if none of the choices are appropriate, I can enter a new string under "Others"

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#12]
For any "tick all that apply" questions (specifically, questions 1, 2, 5, 9, 12, 14, 15, 16, and 17), if none of the existing choices are appropriate, the user can tick "Others" and write her own string in an empty text field next to "Others."

**Comment by antoniocarlosortiz** [comment]
Reviewing Django Dynamic Forms and JS for feasibility.

**Comment by piafaustino** [comment]
@antoniocarlosortiz @stefsy 

If this one will be time-consuming to implement, I have two alternative implementations:

1) We can do away with the tick-boxes. Just give us empty fields in which we can input comma-separated strings. Candice, Mavie and I will just make sure to use a common set of fixed strings, and we have to be careful about avoiding typos.

2) You can teach me how to add options to the tickboxes dynamically. That way, I can just add new options as we go along without having to bother Anton. 

Let me know if either of these works!

**Comment by antoniocarlosortiz** [comment]
@piafaustino @stefsy

The feature can be done. However, on the Others Field, the format should be uniform, i.e., tiehter comma-separated or hashtags. @stefsy What do you think?

**Comment by antoniocarlosortiz** [comment]
@piafaustino for your review.

**Comment by stefsy** [comment]
That works as long as we define a scheme.

Tags separated by spaces, people by commas?

Eg "

**Comment by piafaustino** [comment]
@antoniocarlosortiz @stefsy Which solution do you want to implement? The original one, or alternatives 1 or 2?

**Comment by stefsy** [comment]
Let's go with option 1

e.g, for 3 injured people enter the ff string in the field. 

male 45 injured driving, female 8, motorcyclist

**Comment by piafaustino** [comment]
Got it! :+1: @antoniocarlosortiz

**Comment by piafaustino** [comment]
Wait a sec! @stefsy, your "tags separated by spaces, people by commas" solution would solve issues #17 #16.  This issue is a bit different. It's about allowing for an "others" field. Maybe best to have a super quick sync on these solutions soon. I'm free anytime today, how about you guys? @antoniocarlosortiz

**Comment by stefsy** [comment]
Whoops! I was in a meeting until now! I'm totally sorry I replied to the
wrong issue. Will be home in 30 mins and clarify

**Comment by piafaustino** [comment]
No worries! Puwede rin tomorrow?
