### ISSUE TITLE
Pre-populate "number of killed" field with numbers culled from scrape

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#13]
For question 6a in the survey, which asks for the number of people killed in the road crash, the field will be pre-populated with numbers acquired through automated means.

However, the user can modify this number.

The same implementation will be done with "number of injured" (Issue #15)

**Comment by antoniocarlosortiz** [comment]
Reviewing string and and Django Field manipulation for feasibility.
