### ISSUE TITLE
Change Question 15 (statistics) to tick-all-that-apply

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#14]
For Question 15: What scope of statistics on road safety are used?

The question is currently implemented as multiple-choice. Please modify so that the user can instead tick all that apply.

**Comment by antoniocarlosortiz** [comment]
On track to finish by EOD

**Comment by antoniocarlosortiz** [comment]
@piafaustino may I ask what should be the choices for this? On the initial set of questions that I used, there were no other options except for yes or no.

**Comment by piafaustino** [comment]
@antoniocarlosortiz You're right, sorry, this should refer to Question 15.

**Comment by antoniocarlosortiz** [comment]
@piafaustino for your review.
