### ISSUE TITLE
Pre-populate "number of injured" field with numbers culled from scrape

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#15]
For question 7a, which asks for the number of people injured in the road crash, the field should be pre-populated with numbers acquired through automated means. However, the user can also manually change this number.

The same implementation will be done with "number of killed" (Issue #13)

**Comment by antoniocarlosortiz** [comment]
Reviewing string and and Django Field manipulation for feasibilty.

**Comment by antoniocarlosortiz** [comment]
This can be done but please take note the question may easily be skipped if the user is going through numerous articles and the field is already filled up right from the start. What I would suggest is that we place the results of the scrape on top of the questions instead to serve as a guide as opposed to the input field as automatically being filled up. For your review. Thank you.

**Comment by piafaustino** [comment]
Okay that's fine too @antoniocarlosortiz . We don't mind doing this manually -- just didn't want to waste your effort in trying to scrape it! :)

**Comment by antoniocarlosortiz** [comment]
Thanks @piafaustino!
