### ISSUE TITLE
User can input descriptive words/phrases about each road crash fatality

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#16]
In Question 6A, after the user inputs the number of persons killed in a road crash, an equal number of empty text fields will appear below, under Question 6B.

This is how it should look, for example, after a user writes that 5 persons were reported killed in a certain road crash report:

```
6a. How many victims were killed in the car crash? [  5  ]
6b. How many of the fatalities were described in further detail and how?
   Victim 1  [_________________________]
   Victim 2  [_________________________]
   Victim 3  [_________________________]
   Victim 4  [_________________________]
   Victim 5  [_________________________]
```

In each empty field, the user can write a string of descriptive words or phrases about the victim. Each descriptive word or phrase is separated by a comma. For example: 

```
   Victim 1  [ mother, female, 45, businesswoman]
```

If a victim is not described in any way, the user can just leave the field blank.

---

Note: Same implementation for persons killed -- Issue #17

**Comment by antoniocarlosortiz** [comment]
Reviewing creation of dynamic django forms and js for feasibility.

**Comment by antoniocarlosortiz** [comment]
@piafaustino @stefsy This would take long to do. May I ask if we can convert this instead to a charfield and user creates a list for each victim and then separate them with a comma? For example: [male, 45, businessman],[female, 32, politician] . @stefsy May I ask what do you think of this?

**Comment by antoniocarlosortiz** [comment]
@piafaustino for your review.
