### ISSUE TITLE
User can input descriptive words/phrases about each injured person

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#17]
In Question 7A, after the user inputs the number of persons injured in a road crash, an equal number of empty text fields will appear below, under Question 7B.

This is how it should look, for example, after a user writes that 5 persons were reported injured in a certain road crash report:

```
7a. How many victims were injured in the car crash? [  5  ]
7b. How many of the injured were described in further detail and how?
   Victim 1  [_________________________]
   Victim 2  [_________________________]
   Victim 3  [_________________________]
   Victim 4  [_________________________]
   Victim 5  [_________________________]
```

In each empty field, the user can write a string of descriptive words or phrases about the injured person. Each descriptive word or phrase is separated by a comma. For example: 

```
   Victim 1  [ mother, female, 45, businesswoman]
```

If a victim is not described in any way, the user can just leave the field blank.

---

Note: This is the same implementation for persons killed, described in issue #16

**Comment by antoniocarlosortiz** [comment]
Reviewing creation of dynamic django forms and js for feasibility.

**Comment by antoniocarlosortiz** [comment]
@piafaustino @stefsy This would take long to do. May I ask if we can convert this instead to a charfield and user creates a list for each victim and then separate them with a comma? For example: [male, 45, businessman],[female, 32, politician] . @stefsy May I ask what do you think of this?

**Comment by piafaustino** [comment]
This seems OK -- how about though instead of writing the lists that way using brackets (might be error prone), we have a string of tags separated by commas, and each person is on its own line. 

So for example, we'll record the victims from this article "2 dead, 9 injured in Albay road accident" https://traffic-news.herokuapp.com/post/130/edit/ as so:

DEAD:
Aliza Daza, female, 10 years old, dead on the spot, thrown off motorcycle, run over by the truck
Michael Pante, age unknown, male, cause of death unknown

INJURED:
Rodrigo Murillo, male, grandfathe, driving motorcycle
Joey Salvador, truck driver, would be detained after treatment
unknown
unknown
unknown
unknown
unknown
unknown
unknown

**Comment by antoniocarlosortiz** [comment]
@piafaustino for your review.
