### ISSUE TITLE
User can create #hashtags to group multiple articles on the same road crash event

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#18]
For Question 8, the user can add a #hashtag to identify a news article that is part of an ongoing news story or coverage theme.

For example, news organizations will often publish many stories about a single incident. For example, there are multiple articles in our database about the "Bontoc Bus Tragedy" -- a bus accident that claimed 32 lives in February 2014. All these articles can be tagged #bontocbustragedy so that later, during the data analysis, we can see that they are actually all about a single road accident.

**Comment by antoniocarlosortiz** [comment]
On track to finish by EOD

**Comment by antoniocarlosortiz** [comment]
This can accomplished by the current input field. The user just have to write the #bondocbustragedy and on the final result, itll be easy to filter articles depending on the hashtag. For your review on closing this issue. Thank you!

**Comment by piafaustino** [comment]
@antoniocarlosortiz copy, closing!
