### ISSUE TITLE
Create a way for the user to note that an article should be excluded from the analysis

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#20]
As we go along during the qualitative analysis, we might encounter other articles that should be excluded from the study because they are irrrelevant or international. We should be able to note that these articles should be excluded from the analysis-- perhaps there can be an "EXCLUDE" tickbox at the top of the survey.

It would also be nice if we could filter our excluded articles, but not totally necessary. :)

**Comment by antoniocarlosortiz** [comment]
On track to finish by EOD

**Comment by piafaustino** [comment]
@antoniocarlosortiz 

I noticed there's an INCLUDED/EXCLUDED filter at the top of the survey. Are these filters?

I ticked "Exclude" on article 2584 "Google self-driving car coming around the corner" to see if that would make it appear under the EXCLUDED filter. But it didn't.

**Comment by antoniocarlosortiz** [comment]
You are right. It does not work. 'Will fix this immediately.

**Comment by antoniocarlosortiz** [comment]
@piafaustino issue #20 fixed. For your review.

**Comment by piafaustino** [comment]
@antoniocarlosortiz Okay checking! Favor - could you assign me to Github issues that you've resolved and need QA/closing? Also making tags for "resolved" and "in progress"

**Comment by piafaustino** [comment]
Checked it. It looks like it works, but I have a suggested enhancement. Make "INCLUDED" the DEFAULT FILTER. Currently, the app displays both INCLUDED/EXCLUDED by default.
