### ISSUE TITLE
User should be able to easily navigate to "previous" or "next" article with one click

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#21]
After reading and completing the survey about an article, a user should be able to navigate to either the next or previous article with one click. There could be two buttons at the bottom of the page -- one that says "Previous Article" and another that says "Next Article."

(Currently, the user has to return to the main index and navigate to the next article from there)

In relation to this, the user should be able to see each article's unique ID number in both the main index and individual article pages (Issue #22)

**Comment by antoniocarlosortiz** [comment]
Reviewing ordering on Django Queryset sorting method for feasibility.

**Comment by piafaustino** [comment]
@antoniocarlosortiz I don't previous/next buttons in the survey form.

**Comment by antoniocarlosortiz** [comment]
@piafaustino

**Comment by piafaustino** [comment]
@antoniocarlosortiz Could you name your pull requests/commits in a way that I can tell what bug you're fixing or feature you're adding? :)

**Comment by piafaustino** [comment]
There's also a bug with this implementation.

Reproduction.
1. In the filters, I click on "Rater: Pia." I click "Go." The articles refresh to include only articles for which Rater = Pia.
2. I click on the second article in the list.
3. I click the "Back" Button.
4. I land on an article in which "Rater = Mavie."


Same happens if I click on the "Next" button. The article is one that's assigned to Mavie, not me. There needs to be a way for the filters to stick. :)

**Comment by stefsy** [comment]
@antoniocarlosortiz +1 on good naming for commits

suggestion @antoniocarlosortiz @piafaustino, can we drop this requirement and remove the previous/next buttons? creating dynamic logic for the previous/next buttons is difficult under the current implementation. Instead, what if we had the links open in new tabs as a default, and the journalist team just keeps the main view with filters perpetually open?

**Comment by piafaustino** [comment]
@antoniocarlosortiz @stefsy Okay that will do. :)

**Comment by piafaustino** [comment]
So let's file a separate issue for this feature: "From the main index, article links open in a new tab."
