### ISSUE TITLE
Add a survey question about the location of the road crash.

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#23]
Please add an additional survey question that will allow the user to input the *location* of a road crash.

Let's make it Question 10, and the inputs can be blank fields or drop-down menus (please suggest the best implementation) where the user can input the region, city/municipality, and specific location such as street or barangay.

10 - What's the location of the road crash? 
Region: [______________]
City/Municipality: [_______________]
Specific location:  [_______________]

Succeeding survey questions will be renumbered accordingly.

**Comment by antoniocarlosortiz** [comment]
Good day Pia. This can be done within the next 24 hrs.

**Comment by antoniocarlosortiz** [comment]
It would  be better if it's just a blank field as a drop down menu would require a database of all the locations defined down to the street level.

**Comment by piafaustino** [comment]
@antoniocarlosortiz Sure a blank field is fine too!
