### ISSUE TITLE
Enhancement: Enable simultaneous filtering.

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#24]
In the current app, you can only use one filter at a time. However, it's better if the users can activate more than one filter simultaneously.

Reproduction of current behavior:
1. Activate/click the filter for "Pia." Articles displayed are only those for which Rater = Pia.
2. Activate/click the filter for "Included." Articles displayed now belong to all three Raters = Mavie, Candice, and Pia. 
3. Activate/click the filter for "Mavie." Article displayed are only those for which Rater = Mavie.
4. Activate/click the filter for "Excluded." Articles displayed are excluded articles (there are only two right now) but Rater = Pia for both.

Desired behavior:
Ideally, a filter should remain active unless a person clicks it a second time to turn it "Off." Also, the user should be able to use multiple filters simultaneously.

**Comment by antoniocarlosortiz** [comment]
@piafaustino For your review.

**Comment by piafaustino** [comment]
@antoniocarlosortiz 

There's a bug in execution. The filters reset when I click to the next results page.

Reproduction:
1. In the main index, I click on filters "Rater: Pia", "Completed: No", "News Type: Text", and "Exclude: No."
2. I scroll down and click to the next page.
3. I'm now on the next page of results, but all the filters I had ticked have disappeared. 

BTW, please assign me to issues that you want QA'd. I'll close the issue if the result works, but I'll re-assign it back to you if there are problems. :)

**Comment by antoniocarlosortiz** [comment]
@piafaustino Thank you. Ill start assigning you. Also, for your review.

**Comment by piafaustino** [comment]
It works!
