### ISSUE TITLE
Add new question: What time of day did the accident take place? 

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#26]
Please insert this question as the new Question 11. It can be a blank text field as the answer, because sometimes the specific time of day is not given -- only "morning" or "afternoon" etc.

Kindly place this question after "10. What’s the location of the road crash?" and before "11. Does the report relate the accident to a broader cause or mention a larger context? "

Cascade subsequent question numbers accordingly.

**Comment by antoniocarlosortiz** [comment]
@piafaustino For your review. Thank you!
