### ISSUE TITLE
Enhancement for implementation of Question 13 (What solutions to road safety are mentioned?)

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#29]
Currently, there are a number of possible responses to Question 13, which asks the rater to tick road safety solutions mentioned in the article:

![screen shot 2015-05-11 at 9 27 03 am](https://cloud.githubusercontent.com/assets/1260018/7557227/0064b772-f7c0-11e4-83a0-797dc9a30f29.png)

However, I recently learned that these solutions can also be grouped into five broad categories:
1. Safer road management 
2. Safer road infrastructure
3. Safer vehicles 
4. Safer road users (focused on individual behavior like helmet wearing, seatbelts, etc)
5. Better post-crash response

In the final analysis, we would like to be able have a breakdown of both the broad categories and specific solutions mentioned.

What's the best way to achieve this?

Some options:
1) Should we add another question "What categories of road safety solutions are mentioned?"

2) Should we leave Question 13 as is, but in the final analysis, retroactively identify the category to which each specific solution belongs?

**Comment by stefsy** [comment]
Do you have a list of which solutions belong to what category? Is it a one-to-one relationship? 

Easier to group them all computationally afterwards that have human raters fill in two fields. (Human raters == human error)

**Comment by stefsy** [comment]
test test

**Comment by piafaustino** [comment]
Okay got it! Specific solutions can belong to more than one category, but it's easy enough to just pick a primary one. Here's a rough breakdown:

1. Safer road management
- Reducing of/ better enforcement of speed limits
- Improved traffic enforcement
- Driver’s license regulation
- Public transport regulation
- Vehicle registration
- Improvement of working conditions in transport sector

2. Safer road infrastructure
 - Improvement of infrastructure
 - Improvement of public transport
 - Installation of road signs

3. Safer vehicles
- Enforcement of automotive industry standards
- New vehicle technology
- Improved vehicle maintenance
- Vehicle safety inspections

4. Safer road users
- Improvement of Driver Education
- Improvement of Pedestrian Education
- Use of helmets
- Use of seat belts
- Avoiding mobile use while driving

5. Better post-crash response

**Comment by stefsy** [comment]
@piafaustino  can you create an Analysis milestone and file this issue there?

**Comment by piafaustino** [comment]
@stefsy Yes will do!

**Comment by piafaustino** [comment]
@antoniocarlosortiz Sorry, it appears I closed this discussion before you were able ot read it. Regarding the changes you made to Question 13 (road safety solutions) -- please see discussion of @stefsy and myself above. @stefsy recommended we retain the SPECIFIC solutions in the survey, and instead categorize them during the analysis process.

Please revise Question 13 again as follows:

13. What interventions/solutions to road safety problems are mentioned in the article?
- [ ] Enforcement of speed limits
- [ ] Reduction of speed limits
- [ ] Improvement of traffic enforcement
- [ ] Stricter driver’s license regulation
- [ ] Stricter public transport franchise regulation
- [ ] Improvement of working conditions in transport sector
- [ ] Implementation of safety inspections on public transport
- [ ] Improvement of road infrastructure
- [ ] Improvement of infrastructure for pedestrians
- [ ] Improvement of infrastructure for cyclists
- [ ] Improvement of mass public transport infrastructure
- [ ] Installation of road signs
- [ ] Improved visibility or accuracy of road signs
- [ ] Stricter automotive industry standards
- [ ] Better enforcement of automotive industry standards
- [ ] Safer vehicle technology
- [ ] Improved vehicle maintenance
- [ ] Road user education
- [ ] Use of helmets
- [ ] Use of seat belts
- [ ] Avoiding mobile use while driving
- [ ] Use of child restraints
- [ ] Improvement of post-crash emergency response
- [ ]  Others: ___
