### ISSUE TITLE
In the main index, article links open to new window

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#30]
Branched from Issue #21.

**Comment by antoniocarlosortiz** [comment]
@piafaustino @stefsy may I ask if you could rephrase the issue? Do the buttons create a new window or do the users want those to create one when pressed? If the latter holds true, specifically what links or buttons should we update for this? Thank you!

**Comment by stefsy** [comment]
@antoniocarlosortiz i'm saying remove the previous/next buttons entirely. the only links should be the links from the main view to the article. click link -> link opens in new window. makes sense?

**Comment by piafaustino** [comment]
So right now if you click the title of an article in the main index, it
opens that article page within the same window. Desired execution is that
individual articles open into a separate window. This means the index page
remains open with whatever active filters the user has ticked

**Comment by antoniocarlosortiz** [comment]
@piafaustino For your review. Thank you!

**Comment by piafaustino** [comment]
@antoniocarlosortiz Kindly check again our replies to your request for clarification.

@stefsy recommended that we just remove altogether the "previous" and "next" buttons. This is because when a user clicks the "next" button, the next article that opens does not consider the user's active filters.

For example, I filter my articles for "rater = Pia." But after I click the 'next ' button, I will see an article assigned to Mavie. Plus, when I go back to the Index, the filters have been reset and I have to input them all over again.

Stef recommended that the users just open each article in a new, separate tab. This way we can keep the index intact with its active filters, and we don't have to keep re-setting the filters.

So we just need you to set the article links to open into new tabs, rather than within the same tab:
![screen shot 2015-05-11 at 7 19 43 pm](https://cloud.githubusercontent.com/assets/1260018/7563796/1315924e-f813-11e4-9a05-065400328cec.png)

Make sense?

**Comment by antoniocarlosortiz** [comment]
@piafaustino Got it. Thanks for the clarification.

**Comment by piafaustino** [comment]
Works great!
