### ISSUE TITLE
Categorize specific road safety interventions into 5 broad categories

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#31]
Branched from Issue #29 

In the ANALYSIS, specific road safety solutions/interventions in Question 13 will be categorized into the following

5 Categories of Road Safety Interventions:
1. Safer road management
2. Safer road infrastructure
3. Safer vehicles
4. Safer road users
5. Better post-crash response

**Comment by piafaustino** [comment]
Sorry @antoniocarlosortiz, this issue is for the Analysis milestone not for the Survey Interface. I should have made that clearer. Kindly refer to discussion on issue #29

**Comment by antoniocarlosortiz** [comment]
@piafaustino Can I ask if this is already safe to close?

**Comment by piafaustino** [comment]
It's something we'll execute during Analysis. So let's keep it open
