### ISSUE TITLE
Changing filter "completed=no" to "completed=yes" results in Server Error 500

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#34]
I had these filters active:
![screen shot 2015-05-11 at 7 55 53 pm](https://cloud.githubusercontent.com/assets/1260018/7564297/dcca62a0-f817-11e4-811d-977ba053a17e.png)

Then I changed it to these filters:
![screen shot 2015-05-11 at 7 55 18 pm](https://cloud.githubusercontent.com/assets/1260018/7564307/eb790766-f817-11e4-842d-31149eaedb11.png)

When I clicked "go" I got a server error 500.

**Comment by antoniocarlosortiz** [comment]
@piafaustino Is it alright if you check it again? I might have been solving bugs at that time while you checked it :)

**Comment by piafaustino** [comment]
@antoniocarlosortiz Looks like it works na!
