### ISSUE TITLE
Proposed enhancement for Question 5B: Include # of each vehicle involved in crash

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#35]
Question about a possible enhancement for Question 5B. Some reports also identify the specific number of each vehicle type involved in a crash.  This might also be useful info for us to record, the same way we are doing with number of injured / killed.

For example:
4 motorcycles
2 ten-wheeler trucks
1 pedicab

So for Question 5B, what do you think about replacing the tickboxes with charfields where we can input numbers instead?

It would look like this:
![screen shot 2015-05-12 at 11 38 19 am](https://cloud.githubusercontent.com/assets/1260018/7579794/048c6ac0-f89c-11e4-9c37-5dd0b3e8b024.png)

**Comment by stefsy** [comment]
Do you have a specific hypothesis or bit of analysis you will use this for? Otherwise, this is a nice to have bit of information that will take up another 4-6 hours in terms of database redesign. value/effort ratio doesn't look worthwhile.

**Comment by piafaustino** [comment]
DOTC reports that 60 to 70% of road crashes in the Philippines involve vehicles with fewer than three wheels (motorcycles, bicycles, and tricycles).  But if this change will take 4-6 hours redesign time, then we can just use the current set-up to derive an approximately similar ratio. The only limitation is that our analysis won't distinguish between a road crash involving 6 motorcycles + 1 truck from a crash involving 1 motorcycle + 1 truck. But, I think that's okay.
