### ISSUE TITLE
Suggested tweaks to syntax for describing injured/killed persons

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#36]
Could we make some tweaks to improve readability of injured/killed descriptors?

Suggestions:
1. Data labels end with a colon
2. One person = one line ended with a backslash (because we noticed the text wraps automatically so what looks like two lines may actually be just one line)

Example:
name: Mavie Ungco, age: 30, gender: female, ridergroup: motorcycle passenger, causeofdeath: thrown from motorcycle /

Also, if no data at all is known about a passenger, is it okay if we just leave it blank rather than write "unknown?" Reason being: If there 10 fatalities total but only 4 lines in this particular field, then we know that the remaining 6 victims are unknown by default. No need so spell it out.

**Comment by stefsy** [comment]
sounds good! we can handle this on the data processing/analysis end

**Comment by piafaustino** [comment]
Great, will add the "Style Guide" that we're using to our Wiki.

**Comment by antoniocarlosortiz** [comment]
@piafaustino Can I ask if we can already close this issue?

**Comment by piafaustino** [comment]
Okay, it's in Wiki instead
