### ISSUE TITLE
Limit videos to those that contain a few key road safety phrases

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#37]
Here's our long overdue feedback on what to do regarding the videos!

While our text reports included a lot of reports on specific road crash incidents, we will limit our videos to those that offer a macro perspective on road safety.

Please limit our sample videos to those published in 2014 on the GMA and ABSCBN YouTube channels and whose headlines or descriptions contain the following key phrases:

"road accidents"
"accidents"
"mga" + "aksidente"
"road safety"

We just need these in a Google spreadsheet. No need to do a survey interface like before, since we're pretty confident the sample will be quite small!

**Comment by antoniocarlosortiz** [comment]
@piafaustino @stefsy I believe it would be better if I put an exclude tag on video entries that do not have the said keyframes. Would this be alright?
