### ISSUE TITLE
Please add 3 tickbox options for Question 16 (sources)

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#39]
Could we add just three more tickbox options to Question 16?
- [ ] PNP Highway Patrol Group
- [ ] LTO
- [ ] LTFRB

**Comment by antoniocarlosortiz** [comment]
@piafaustino yes we can.

**Comment by benigeri** [comment]
#Obama








On Friday, May 15, 2015 at 9:33 PM, antoniocarlosortiz <notifications@github.com>, wrote:

@piafaustino yes we can.

**Comment by piafaustino** [comment]
@antoniocarlosortiz Thanks. Could you give a turnaround time estimate, please?
