### ISSUE TITLE
Syntax suggestion re: how to treat multiple victims with limited info

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#41]
If there are more person than one killed or injured in an accident, and we only have very basic and repetitive information about them (ex: the injured were 5 bus passengers), can we write it out like this:

<strong>INJURED:
ridergroup: bus passenger * 5</strong>

Or do we have to write each person 5 times like this:

<strong>INJURED:
ridergroup: bus passenger
ridergroup: bus passenger
ridergroup: bus passenger
ridergroup: bus passenger
ridergroup: bus passenger</strong>

**Comment by antoniocarlosortiz** [comment]
I think this format will still be ok. I dont see any issues with it but can I ask for your opinion on this @stefsy?

**Comment by piafaustino** [comment]
Oops we're using backslashes now at the end so how about

ridergroup: bus passenger/ * 13

OR

ridergroup: bus passenger * 13 /

**Comment by piafaustino** [comment]
@stefsy @antoniocarlosortiz is this OK to use?

**Comment by stefsy** [comment]
@piafaustino prefer using the / character as a stop character rather than * 

__ridergroup: bus passenger * 13/__ is preferred

**Comment by piafaustino** [comment]
Got it!
