### ISSUE TITLE
The user can filter the articles according to who is assigned to rate them.

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/in-the-news#9]
The user can filter the articles according to who is assigned to rate them. Clicking on the name of the assigned rater (either Mavie, Candice, or Pia) will hide other articles not assigned to that person. The active filter is displayed in bold.

![screen shot 2015-04-29 at 5 23 31 pm](https://cloud.githubusercontent.com/assets/1260018/7388087/0b566862-ee95-11e4-938a-3af8e3673eeb.png)

**Comment by piafaustino** [comment]
@antoniocarlosortiz You may use these values for the first 900 articles:

1-300 - Mavie
301-600 - Candice
601-900 - Pia

**Comment by antoniocarlosortiz** [comment]
@piafaustino for your review.

**Comment by piafaustino** [comment]
Hi Anton! I'm getting an internal server error when I try to access the site.

**Comment by piafaustino** [comment]
This works, but see enhancement suggestion #24
